'use strict';
const bb=(slug)=>`https://www.bbc.co.uk/bitesize/${slug}`;
const resources={static:[['Static electricity: photographs and charge diagrams',bb('topics/zgy39j6/articles/zshqqfr')],['Electrostatic sparks and shocks',bb('topics/zgy39j6/articles/zshqqfr')]],circuits:[['Circuit symbols and meter diagrams',bb('articles/zjm8kty')],['Series circuit photographs and diagrams',bb('topics/zgy39j6/articles/zs3htrd')],['Parallel circuit photographs and diagrams',bb('topics/zgy39j6/articles/z34yf82')]],magnet:[['Electromagnetism: wire and solenoid diagrams',bb('topics/z3sf8p3/articles/z7922v4')],['Magnetic effects of current',bb('topics/zgw7vj6/articles/z6yhcxs')]]};
const svg=(name)=>`<img class="diagram" src="./${name}.svg" alt="${({charge:'Positive and negative charge transfer from rubbing',circuit:'Circuit containing an ammeter in series and voltmeter in parallel',magnet:'Magnetic field lines around bar magnet'})[name]}">`;
const sections=[
{id:'charge',name:'Charge and fields',short:'Particles, forces and charge',icon:'＋ −',intro:'Explain charge using electrons, and predict attraction and repulsion.',lessons:[
['Charge and electric fields',`${svg('charge')}<p>Protons have positive charge and electrons have negative charge of equal magnitude. A neutral object has equal amounts of positive and negative charge. Gaining electrons makes an object negative; losing electrons makes it positive. Protons stay in the nucleus when objects are charged.</p><p>Like charges repel; opposite charges attract. A charged object can also attract a neutral object because charge rearranges within it. An <strong>electric field</strong> is a region where a charge experiences a force without contact. Greater charge gives a stronger force; greater separation gives a weaker force.</p>`],
['Charging by friction, conduction and induction',`<p><strong>Friction:</strong> rubbing two different insulators transfers electrons. One gains electrons and becomes negative; the other loses electrons and becomes positive. <strong>Conduction:</strong> a charged conductor touches another conductor, allowing electrons to flow and charge to be shared. <strong>Induction:</strong> a nearby charged object redistributes charge without touching. A conductor allows mobile electrons to move; in an insulator charges shift locally.</p><p>A negatively charged rod near neutral paper repels electrons slightly farther away, leaving the near side effectively positive. The nearer attraction can exceed the farther repulsion, so the paper moves toward the rod.</p>`],
['Discharging, sparks and lightning',`<p>Earthing provides a path for electrons to flow to or from the Earth until excess charge is reduced. A large potential difference can create a strong enough electric field to make normally insulating air conduct: a spark jumps the gap. In storms, charge separation in clouds induces opposite charge on the ground. Tall or pointed objects can experience stronger fields and are more likely points for a lightning discharge.</p><p><strong>Safety:</strong> never experiment with mains electricity or thunderstorms. In class, use the teacher's low voltage apparatus.</p>`]],checks:[['A neutral object gains electrons. What charge does it acquire, and why?','Negative: it now has more electrons than protons.'],['Why can a charged balloon attract a neutral paper scrap?','It polarises the paper; the opposite charge on the closer side gives a greater attractive force than repulsion from the farther side.'],['What moves when a plastic rod is charged by rubbing?','Electrons transfer between the materials; protons do not move from their nuclei.'],['How does earthing discharge a positively charged metal object?','Electrons flow from the Earth to the object until its charge is reduced.']],resource:'static'},
{id:'circuits',name:'Circuits and quantities',short:'Current, voltage and resistance',icon:'⏚',intro:'Describe a complete DC circuit and how to measure its electrical quantities.',lessons:[
['DC current and potential difference',`${svg('circuit')}<p>A closed conducting loop is needed for steady current. Current is the rate of flow of charge, measured in amperes (A). Electrons move toward the positive terminal; <strong>conventional current</strong> is drawn from the positive terminal to the negative terminal outside the supply. A DC supply maintains one direction of current.</p><p>Potential difference is energy transferred per unit charge, measured in volts (V). Resistance opposes the flow of charge, measured in ohms (Ω). Longer, thinner wires generally have more resistance; temperature also matters.</p>`],
['Measuring in circuits',`<p>An ammeter goes <strong>in series</strong> so current flows through it. It is designed to have very low resistance. A voltmeter goes <strong>in parallel</strong> across a component and has very high resistance. Use the correct circuit symbols, draw straight wires and connect every branch clearly. An unintended very low resistance path may short circuit a component and cause a large current.</p>`],
['Ohm’s law and power',`<p class="formula">V = IR &nbsp;&nbsp; P = VI</p><p>For a fixed resistor at constant temperature, voltage is proportional to current. On a graph of voltage (vertical axis) against current (horizontal axis), the gradient is resistance. Electrical power is the rate of energy transfer, measured in watts (W). With the same resistance, increasing current raises the power dissipated; a lamp may become brighter, though a filament lamp is not a constant resistance resistor.</p><p><strong>Example:</strong> 6 V across a 3 Ω resistor gives I = V/R = 2 A and P = VI = 12 W.</p>`]],checks:[['A 12 V supply is connected across a 4 Ω fixed resistor. Find the current.','I = V/R = 12/4 = 3 A.'],['Where should a voltmeter go to measure voltage across a lamp?','In parallel with the lamp.'],['What does the gradient of a V against I graph represent?','The resistance R, provided V is the vertical axis and I the horizontal axis.'],['Why is a filament lamp not always described by a straight V–I line?','Its filament heats up and its resistance changes as current increases.']],resource:'circuits'},
{id:'networks',name:'Series and parallel',short:'Loops, junctions and power',icon:'⌁',intro:'Apply current, voltage and resistance rules to simple and mixed circuits.',lessons:[
['Series rules',`<p>A series circuit has one path: current is the same through each component. Resistances add: <span class="formula">R<sub>total</sub> = R₁ + R₂ + …</span> The supply voltage equals the sum of voltage drops around the loop. Adding a resistor in series increases total resistance and decreases total current for a fixed supply.</p><p><strong>Example:</strong> 2 Ω and 4 Ω in series on a 12 V supply give 6 Ω total and 2 A. The voltage drops are 4 V and 8 V.</p>`],
['Parallel rules and junctions',`<p>Branches form separate conducting paths. Total current entering a junction equals total current leaving it. Each parallel path between the same two nodes has the same potential difference. A branch with lower resistance carries more current. Adding a parallel branch lowers the total resistance and increases the supply current for an ideal fixed voltage supply. Current is <em>not used up</em>.</p><p><strong>Example:</strong> 6 Ω and 3 Ω in parallel across 6 V draw 1 A and 2 A respectively; the supply current is 3 A.</p>`],
['Mixed circuits',`<p>Work from a clearly labelled diagram: identify which components share the same two nodes, find the current in each branch with V = IR, add branch currents at each junction, and check each loop's voltage drops add to the supply voltage. For a series resistor before a parallel pair, the supply voltage is shared between the series resistor and the entire parallel block.</p>`]],checks:[['Two resistors of 3 Ω and 5 Ω are in series. Find total resistance.','8 Ω.'],['At a junction, 1.2 A enters. One branch carries 0.5 A. Find the other.','0.7 A leaves in the other branch.'],['Why are lamps on separate parallel branches still lit if one branch opens?','Other branches still have complete conducting paths across the supply.'],['An ideal 9 V supply has two branches. What is the voltage across each branch?','9 V, provided each branch connects directly across the supply.']],resource:'circuits'},
{id:'magnetism',name:'Magnetic fields',short:'Poles, lines and Earth',icon:'N S',intro:'Read and draw magnetic field diagrams and distinguish permanent from induced magnetism.',lessons:[
['Magnetic materials and interactions',`${svg('magnet')}<p>Like magnetic poles repel; unlike poles attract. A magnet can attract an unmagnetised ferromagnetic object because it induces magnetism in it. Iron, nickel and cobalt are ferromagnetic. An induced magnet has both poles while magnetised; the near end becomes the opposite pole to the approaching magnet, so attraction occurs regardless of which pole approaches. Some materials retain magnetism after the external field is removed; others lose most of it.</p>`],
['Magnetic field lines',`<p>A magnetic field is a region where a magnetic object experiences a force. Outside a bar magnet, field lines go from <strong>north to south</strong>; they form closed loops when the path inside the magnet is included. Closer line spacing indicates a stronger field, usually near the poles. The field weakens with distance. Straight, parallel, equally spaced lines indicate an approximately uniform field. Earth also has a magnetic field, which influences a compass needle.</p>`]],checks:[['A north pole approaches an unmagnetised iron nail. What is induced at the near end?','A south pole; the nail is attracted.'],['Does an induced magnet have only one pole?','No. It has north and south poles while magnetised.'],['What do closely spaced magnetic field lines show?','A stronger magnetic field.'],['In which direction do field lines point outside a bar magnet?','From north to south.']],resource:'magnet'},
{id:'electromagnet',name:'Current and magnetism',short:'Wires, solenoids and uses',icon:'◎',intro:'Predict the field around a wire and solenoid and explain electromagnet applications.',lessons:[
['Field around a wire',`<p>A current carrying straight wire produces concentric circular magnetic field lines. The field weakens farther from the wire. For <strong>conventional current</strong>, point your right thumb in the direction of current: your curled fingers show the direction of the magnetic field. A stronger current produces a stronger field. Parallel wires with currents in the same direction attract; in opposite directions they repel.</p>`],
['Solenoids and electromagnets',`<p>A solenoid is a coil of wire. Its field resembles that of a bar magnet, with a relatively uniform field inside. Curl the fingers of your right hand in the conventional current's direction around the coil; your thumb points to its north pole. Looking at one end, anticlockwise current indicates a north pole; clockwise indicates south. More current or more turns produces a stronger field. Adding an iron core strengthens the field because the iron becomes magnetised.</p><p>An electric bell or door lock uses a current controlled electromagnet to attract a moving iron part. Switching off the current weakens the field so a spring can return the part.</p>`]],checks:[['A straight wire carries conventional current upward. Which hand rule gives the field direction?','Right hand grip rule: thumb upward and curled fingers indicate the circular field.'],['Viewed from one end of a solenoid, current is anticlockwise. Which pole is that end?','North.'],['Give two ways to strengthen a solenoid electromagnet.','Increase current; increase number of turns per unit length; add a suitable soft iron core (any two).'],['Why can an electromagnet operate a door lock remotely?','Switching current on or off changes its magnetic field, which moves an iron armature or latch.']],resource:'magnet'}
];
const exam=[
['A neutral plastic rod is rubbed with a cloth. Electrons move from the cloth to the rod. State the charge on each and explain why. [3]','The rod gains electrons and becomes negative (1). The cloth loses electrons and becomes positive (1). Protons remain in the nuclei (1).','charge'],
['A charged rod attracts small neutral pieces of paper. Explain this observation using induced charge and distance. [4]','Charge is redistributed or polarised in the paper (1). The nearer side has opposite charge to the rod (1). The farther side has like charge (1). The attraction is stronger at the smaller separation than the repulsion, giving a net force toward the rod (1).','charge'],
['Explain how a cloud and ground can produce a lightning strike. Include charge separation, induced charge and the role of air. [4]','Charge separates in the cloud (1), inducing opposite charge on the ground (1). The large potential difference produces a strong electric field (1), which ionises the air so charge can flow as a spark (1).','charge'],
['A 9.0 V supply is connected across a fixed 3.0 Ω resistor. Calculate the current and the power transferred. Show working. [4]','I = V/R = 9.0/3.0 = 3.0 A (2). P = VI = 9.0 × 3.0 = 27 W (2).','circuits'],
['Describe how to connect an ammeter and voltmeter to measure the current through and potential difference across a lamp. Explain the resistance of each meter. [4]','Ammeter in series (1) with very low resistance (1). Voltmeter in parallel across the lamp (1) with very high resistance (1).','circuits'],
['A student graphs voltage V on the vertical axis against current I on the horizontal axis for a fixed resistor. The points (0.20 A, 1.0 V) and (0.60 A, 3.0 V) lie on a straight line. Find the resistance and explain the line’s shape. [4]','Gradient ΔV/ΔI = (3.0−1.0)/(0.60−0.20) (1) = 5.0 Ω (1). V is directly proportional to I (1) if temperature and resistance remain constant (1).','circuits'],
['A 12 V supply is connected to 2 Ω and 4 Ω resistors in series. Calculate total resistance, current and voltage across each resistor. [5]','Rtotal = 2 + 4 = 6 Ω (1). I = 12/6 = 2 A (1). V2Ω = 2×2 = 4 V (1). V4Ω = 2×4 = 8 V (1). The voltage drops add to 12 V (1).','networks'],
['Two parallel branches contain resistors of 6 Ω and 3 Ω. Each branch is directly across an ideal 6 V supply. Find each branch current and the total supply current. [4]','Each branch is at 6 V (1). I6Ω = 6/6 = 1 A (1). I3Ω = 6/3 = 2 A (1). Total = 3 A (1).','networks'],
['An iron nail is attracted by both ends of a bar magnet. Explain why this does not prove the nail is a permanent magnet. State a test that would show the nail is a magnet. [4]','The field induces magnetism in the nail (1). Its near end becomes the opposite pole, so either end attracts (1). Bring a known pole of a magnet toward both ends of the nail (1); repulsion at one end would show it has a fixed pole and is magnetised (1).','magnetism'],
['Describe the pattern and direction of field lines around a bar magnet. Explain how the diagram shows field strength. [3]','Lines emerge from north and enter south outside the magnet (1). Lines curve around and do not cross (1). Closer spacing near poles shows a stronger field (1).','magnetism'],
['State the magnetic field shape around a straight current carrying wire and explain how to determine its direction. What happens farther from the wire? [4]','Concentric circles centred on the wire (1). Right thumb in conventional current direction (1), curled fingers give field direction (1). Field strength decreases farther from the wire (1).','electromagnet'],
['A door lock uses a solenoid with an iron core. Explain how switching on the current releases the latch and give two ways to increase the pull. [5]','Current produces a magnetic field around the coil (1). The iron core becomes magnetised and strengthens the field (1). Magnetic attraction moves the iron armature/latch (1). Increase current (1) and increase turns per unit length (1).','electromagnet']
];
let active='charge',tab='learn';const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function render(){const s=sections.find(x=>x.id===active);document.querySelector('#topics').innerHTML=sections.map(x=>`<button data-topic="${x.id}" class="${x.id===active?'active':''}" aria-current="${x.id===active?'true':'false'}"><strong>${x.icon} &nbsp;${x.name}</strong><small>${x.short}</small></button>`).join('');document.querySelectorAll('.tabs button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));let body=`<div class="section-head"><p class="eyebrow">${s.name.toUpperCase()}</p><h2>${tab==='exam'?'Exam Practice':tab==='check'?'Quick Check':s.name}</h2><p>${tab==='learn'?s.intro:tab==='check'?'Try each question before revealing the model answer.':`Practice original exam style questions. Mark values guide the level of detail.`}</p></div>`;
if(tab==='learn'){body+=s.lessons.map(([title,html])=>`<article class="card"><h3>${title}</h3>${html}</article>`).join('');body+=`<div class="resource"><strong>BBC Bitesize illustrations and explanations</strong><p>Open these BBC pages to inspect the original photographs and diagrams alongside the notes above.</p>${resources[s.resource].map(([label,url])=>`<p><a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a></p>`).join('')}</div>`}
else{const list=tab==='check'?s.checks.map(([q,a])=>[q,a]):exam.filter(q=>q[2]===s.id).map(([q,a])=>[q,a]);body+=`<div class="check-list">${list.map(([q,a],i)=>`<article class="card ${tab==='exam'?'exam':''}"><div class="question">${i+1}. ${esc(q)}</div>${tab==='exam'?'<div class="answer-lines"></div><div class="answer-lines"></div><div class="answer-lines"></div>':''}<button class="reveal" type="button" aria-expanded="false">Show model answer</button><div class="answer" hidden>${esc(a)}</div></article>`).join('')}</div>`}
document.querySelector('#content').innerHTML=body}
document.addEventListener('click',e=>{const topic=e.target.closest('[data-topic]'),mode=e.target.closest('[data-tab]'),reveal=e.target.closest('.reveal');if(topic){active=topic.dataset.topic;render()}if(mode){tab=mode.dataset.tab;render()}if(reveal){const ans=reveal.nextElementSibling;ans.hidden=!ans.hidden;reveal.setAttribute('aria-expanded',String(!ans.hidden));reveal.textContent=ans.hidden?'Show model answer':'Hide model answer'}});render();
