'use strict';
const bb=(slug)=>`https://www.bbc.co.uk/bitesize/${slug}`;
const bbcImage=(src,alt,page,caption)=>`<figure class="bbc-figure"><img loading="lazy" src="${src}" alt="${alt}"><figcaption>${caption} · <a href="${page}" target="_blank" rel="noopener noreferrer">BBC Bitesize ↗</a></figcaption></figure>`;
const video=(id,title,focus)=>`<section class="video-block" aria-label="Year 11 revision video"><div class="video-copy"><strong>Watch and revisit</strong><p>${title} · ${focus}</p></div><div class="video-frame"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/${id}" title="${title}" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><a class="video-fallback" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener noreferrer">Open this video on YouTube ↗</a></section>`;
const ruleCards=(items)=>`<div class="rule-grid">${items.map(([name,rule,measure,example])=>`<section class="rule-card"><h4>${name}</h4><p class="rule-main">${rule}</p><p><strong>How to measure:</strong> ${measure}</p><p><strong>Use it:</strong> ${example}</p></section>`).join('')}</div>`;
const model=(title,steps,finish)=>`<section class="model"><h4>Modelled example · ${title}</h4><ol>${steps.map(step=>`<li>${step}</li>`).join('')}</ol>${finish?`<p class="model-finish">${finish}</p>`:''}</section>`;
const svg=(name)=>`<img class="diagram" src="./${name}.svg" alt="${({charge:'Positive and negative charge transfer from rubbing',circuit:'Circuit containing an ammeter in series and voltmeter in parallel',magnet:'Magnetic field lines around bar magnet',mixed:'Mixed circuit with a 12 V supply, 2 Ω series resistor and two 8 Ω parallel branches carrying 2 A total'})[name]}">`;
const sections=[
{id:'charge',name:'Charge and fields',short:'Particles, forces and charge',icon:'＋ −',intro:'Explain charge using electrons, and predict attraction and repulsion.',lessons:[
['Charge and electric fields',`${bbcImage('https://ichef.bbci.co.uk/images/ic/480xn/p0b9ybrw.jpg','Balloon attracting hair after rubbing',bb('topics/zgy39j6/articles/zshqqfr'),'Static charge in action')}<p>Protons have positive charge and electrons have negative charge of equal magnitude. A neutral object has equal amounts of positive and negative charge. Gaining electrons makes an object negative; losing electrons makes it positive. Protons stay in the nucleus when objects are charged.</p><p>Like charges repel; opposite charges attract. A charged object can also attract a neutral object because charge rearranges within it. An <strong>electric field</strong> is a region where a charge experiences a force without contact. Greater charge gives a stronger force; greater separation gives a weaker force.</p>${model('Predict charge',['A neutral rod has equal positive and negative charge.','Rubbing transfers electrons from a cloth onto the rod. The rod now has an excess of electrons.','The rod is negative and the cloth, having lost electrons, is positive.'],'The protons did not move between objects.')}${video('d7_dMHwqpgM','Year 11 Physics Static Electricity','Pause after the friction example and explain which way electrons move.')}`],
['Charging by friction, conduction and induction',`${bbcImage('https://ichef.bbci.co.uk/images/ic/480x270/p0bh28l3.png','After rubbing: electrons move to the balloon, leaving the jumper positive and balloon negative',bb('topics/zgy39j6/articles/zshqqfr'),'Charging by friction')}<p><strong>Friction:</strong> rubbing two different insulators transfers electrons. One gains electrons and becomes negative; the other loses electrons and becomes positive. <strong>Conduction:</strong> a charged conductor touches another conductor, allowing electrons to flow and charge to be shared. <strong>Induction:</strong> a nearby charged object redistributes charge without touching. A conductor allows mobile electrons to move; in an insulator charges shift locally.</p><p>A negatively charged rod near neutral paper repels electrons slightly farther away, leaving the near side effectively positive. The nearer attraction can exceed the farther repulsion, so the paper moves toward the rod.</p>${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zqhbg7h/large','Negative balloon beside a neutral wall, with positive charge induced on the closer side',bb('topics/zgy39j6/articles/zshqqfr'),'Charge separation explains attraction to a neutral object')}${model('Explain attraction to neutral paper',['The rod makes charges in the paper shift slightly; the paper stays neutral overall.','The near side has an induced opposite charge; the far side has an induced like charge.','The attractive force from the nearer side is greater than the repulsion from the farther side.'],'The paper moves towards the rod without first acquiring a net charge.')}`],
['Discharging, sparks and lightning',`${bbcImage('https://ichef.bbci.co.uk/images/ic/480xn/p09x5wfc.jpg','Spark between charged dome and earthed conductor',bb('topics/zgy39j6/articles/z4h94xs'),'A spark is a brief discharge across air')}<p>Earthing provides a path for electrons to flow to or from the Earth until excess charge is reduced. A large potential difference can create a strong enough electric field to make normally insulating air conduct: a spark jumps the gap. In storms, charge separation in clouds induces opposite charge on the ground. Tall or pointed objects can experience stronger fields and are more likely points for a lightning discharge.</p><p><strong>Safety:</strong> never experiment with mains electricity or thunderstorms. In class, use the teacher's low voltage apparatus.</p>${model('Explain a lightning strike',['Charge separates in a storm cloud and induces the opposite charge on the ground.','The large charge difference creates a strong electric field across the air.','When the air becomes conducting, charge flows rapidly as a spark.'],'Lightning is a large electrostatic discharge.')}`]],checks:[['A neutral object gains electrons. What charge does it acquire, and why?','Negative: it now has more electrons than protons.'],['Why can a charged balloon attract a neutral paper scrap?','It polarises the paper; the opposite charge on the closer side gives a greater attractive force than repulsion from the farther side.'],['What moves when a plastic rod is charged by rubbing?','Electrons transfer between the materials; protons do not move from their nuclei.'],['How does earthing discharge a positively charged metal object?','Electrons flow from the Earth to the object until its charge is reduced.']],resource:'static'},
{id:'circuits',name:'Circuits and quantities',short:'Current, voltage and resistance',icon:'⏚',intro:'Describe a complete DC circuit and how to measure its electrical quantities.',lessons:[
['DC current and potential difference',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zgcgg7h/large','Chart of standard circuit symbols including cell, lamp, resistor, ammeter and voltmeter',bb('articles/zjm8kty'),'Read the symbol before tracing the loop')}${svg('circuit')}<p>A closed conducting loop is needed for steady current. Current is the rate of flow of charge, measured in amperes (A). Electrons move toward the positive terminal; <strong>conventional current</strong> is drawn from the positive terminal to the negative terminal outside the supply. A DC supply maintains one direction of current.</p><p>Potential difference is energy transferred per unit charge, measured in volts (V). Resistance opposes the flow of charge, measured in ohms (Ω). Longer, thinner wires generally have more resistance; temperature also matters.</p>${model('Follow the energy in a circuit',['The supply increases energy per charge. Its potential difference is measured in volts.','Charge flows around a complete circuit; the current is the rate of charge flow.','A component transfers energy from the moving charges to light, heat or movement.'],'Current is not used up by the component.')}${video('rFd-vzU4_pg','Year 11 Physics Circuits Introduction','Watch for circuit symbols, current and potential difference.')}`],
['Measuring in circuits',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zyg23k7/large','BBC circuit showing ammeter in series and voltmeter across a resistor',bb('guides/zpdtv9q/revision/5'),'Meter positions in a measurement circuit')}<p>An ammeter goes <strong>in series</strong> so current flows through it. It is designed to have very low resistance. A voltmeter goes <strong>in parallel</strong> across a component and has very high resistance. Use the correct circuit symbols, draw straight wires and connect every branch clearly. An unintended very low resistance path may short circuit a component and cause a large current.</p>${model('Place meters around a lamp',['To measure the current through a lamp, place the ammeter in the same conducting path as the lamp.','To measure potential difference, connect the voltmeter to the two ends of the lamp.','Check the ammeter is in series and the voltmeter is in parallel.'],'An ammeter has low resistance; a voltmeter has high resistance.')}`],
['Ohm’s law and power',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zgkh4qt/large','BBC graph of current and potential difference for a fixed resistor',bb('guides/zpdtv9q/revision/5'),'A fixed resistor gives a straight line at constant temperature')}<p class="formula">V = IR &nbsp;&nbsp; P = VI</p><p>For a fixed resistor at constant temperature, voltage is proportional to current. On a graph of voltage (vertical axis) against current (horizontal axis), the gradient is resistance. Electrical power is the rate of energy transfer, measured in watts (W). With the same resistance, increasing current raises the power dissipated; a lamp may become brighter, though a filament lamp is not a constant resistance resistor.</p><p><strong>Check the axes:</strong> for voltage V on the vertical axis against current I, the gradient is resistance. Use a V-against-I graph to calculate R from the gradient.</p>${model('Calculate current and power',['Write V = IR and rearrange to I = V/R.','For 9 V across 3 Ω, I = 9 ÷ 3 = 3 A.','Now use P = VI, so P = 9 × 3 = 27 W.'],'Include units at each stage: A for current and W for power.')}${model('Use a V against I graph',['Read two points: (0.20 A, 1.0 V) and (0.60 A, 3.0 V).','Find the rise and run: ΔV = 2.0 V; ΔI = 0.40 A.','Gradient = ΔV/ΔI = 2.0/0.40 = 5.0 Ω.'],'This works because the vertical axis is V and the horizontal axis is I.')}${video('BbizKa6eywo','Year 11 Physics Voltage Current and Resistance','Pause at the graph and check which quantity is on each axis.')}${video('LOyJdI41aCU','Year 11 Physics Power of Components','Follow the P = VI calculation; this video also covers an extension equation.')}`]],checks:[['A 12 V supply is connected across a 4 Ω fixed resistor. Find the current.','I = V/R = 12/4 = 3 A.'],['Where should a voltmeter go to measure voltage across a lamp?','In parallel with the lamp.'],['What does the gradient of a V against I graph represent?','The resistance R, provided V is the vertical axis and I the horizontal axis.'],['Why is a filament lamp not always described by a straight V–I line?','Its filament heats up and its resistance changes as current increases.']],resource:'circuits'},
{id:'networks',name:'Series and parallel',short:'Loops, junctions and power',icon:'⌁',intro:'Apply current, voltage and resistance rules to simple and mixed circuits.',lessons:[
['Series circuits  one path',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zwc7pv4/large','BBC photograph and circuit diagram showing two lamps in series',bb('topics/zgy39j6/articles/zs3htrd'),'Follow the single path through both lamps')}<p>In a <strong>series circuit</strong>, charge has only one route around the loop. Work through the three quantities separately:</p>${ruleCards([
['Current  I','The <strong>same current</strong> flows through every component: I₁ = I₂ = I<sub>supply</sub>.','Put an <strong>ammeter in series</strong>, in the path you want to measure. Move it before or after either component: the reading is the same.','If one ammeter reads 2 A, another anywhere in the same series loop reads 2 A.'],
['Voltage  V','The supply potential difference is <strong>shared</strong> between components: V<sub>supply</sub> = V₁ + V₂.','Put a <strong>voltmeter across</strong> the two terminals of one component. Move it across the supply to read the total, or across each resistor to read its share.','If the supply is 12 V and one component has 4 V across it, the other has 8 V.'],
['Resistance  R','For fixed resistors, the total <strong>adds</strong>: R<sub>total</sub> = R₁ + R₂. More resistance means less current at a fixed supply voltage.','Measure the current through a resistor and the voltage across <em>that same resistor</em>; calculate its resistance using R = V ÷ I.','A 2 Ω and a 4 Ω resistor in series have 6 Ω total.']
])}${model('Series circuit  12 V across 2 Ω and 4 Ω',['Resistance first: Rtotal = 2 + 4 = 6 Ω.','Current next: I = 12 ÷ 6 = 2 A at every point in the loop.','Voltage last: V₁ = 2 × 2 = 4 V; V₂ = 2 × 4 = 8 V.'],'Check: the voltage drops add to 12 V.')}${video('Hk4JEB5DITw','Year 11 Physics Series Circuits','Listen for the current, voltage and resistance rules in order.')}`],
['Parallel circuits  separate paths',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zq9msbk/large','BBC photograph and circuit diagram showing two lamps in parallel',bb('topics/zgy39j6/articles/z34yf82'),'Each branch has its own path')}<p>In a <strong>parallel circuit</strong>, current has a choice of paths at a junction. Branches connected between the same two points share a potential difference. Work through the three quantities separately:</p>${ruleCards([
['Current  I','The supply current <strong>splits</strong> at a junction and recombines: I<sub>supply</sub> = I₁ + I₂. It is not used up.','Place an <strong>ammeter before the junction</strong> for total current, or <strong>inside one branch</strong> for that branch current. Never connect an ammeter across a component.','If the branches carry 1 A and 2 A, the supply ammeter reads 3 A.'],
['Voltage  V','Each complete branch across the same two supply points has the <strong>same voltage</strong>: V₁ = V₂ = V<sub>supply</sub>.','Place a <strong>voltmeter across</strong> each branch, or across the supply. Its probes must touch the two ends of the part being measured.','Across a 6 V supply, each complete branch has 6 V, not 3 V.'],
['Resistance  R','The equivalent resistance is <strong>less than either branch</strong>. Adding a branch lowers the total because there is an additional conducting path.','Measure supply voltage and total supply current, then use R<sub>total</sub> = V<sub>supply</sub> ÷ I<sub>supply</sub>. For one branch use that branch voltage and current.','At 6 V, branch currents of 1 A and 2 A give Rtotal = 6 ÷ 3 = 2 Ω.']
])}${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zp9x6g8/large','BBC junction diagram with 5 A splitting into 3 A and 2 A',bb('topics/zgy39j6/articles/z34yf82'),'Current entering a junction equals current leaving')}${model('Parallel circuit  6 Ω and 3 Ω across 6 V',['Voltage first: both branches have the full 6 V.','Current in each: I₁ = 6 ÷ 6 = 1 A; I₂ = 6 ÷ 3 = 2 A.','Total current: 1 + 2 = 3 A; equivalent resistance: 6 ÷ 3 = 2 Ω.'],'Check: 2 Ω is less than either branch resistance.')}${video('GIvE5Zlpea8','Year 11 Physics Parallel Circuits','Focus on the meter location and what its reading represents.')}`],
['Series and parallel compared',`<p>Choose the rule by tracing the paths before you calculate. Use a voltmeter <strong>across</strong> what you want to measure and an ammeter <strong>in</strong> the path whose current you want.</p><div class="comparison-wrap"><table class="comparison"><thead><tr><th scope="col">Quantity</th><th scope="col">Series  one path</th><th scope="col">Parallel  branches</th></tr></thead><tbody><tr><th scope="row">Current</th><td>Same through every component.<br>I₁ = I₂ = I<sub>supply</sub></td><td>Splits at junctions.<br>I<sub>supply</sub> = I₁ + I₂</td></tr><tr><th scope="row">Voltage</th><td>Shared between components.<br>V<sub>supply</sub> = V₁ + V₂</td><td>Same across complete branches connected to the supply.<br>V₁ = V₂ = V<sub>supply</sub></td></tr><tr><th scope="row">Resistance</th><td>Add the fixed resistors.<br>R<sub>total</sub> = R₁ + R₂</td><td>Total is smaller than the smallest branch.<br>Use R<sub>total</sub> = V<sub>supply</sub> ÷ I<sub>supply</sub> after finding branch currents.</td></tr></tbody></table></div><p class="hint">These resistance calculations assume fixed resistors. A filament lamp's resistance changes as it heats up; use its measured voltage and current at the operating point.</p>`],
['Mixed circuits',`${svg('mixed')}<p>Work from a clearly labelled diagram: identify which components share the same two nodes, find the current in each branch with V = IR, add branch currents at each junction, and check each loop's voltage drops add to the supply voltage. For a series resistor before a parallel pair, the supply voltage is shared between the series resistor and the entire parallel block.</p>${model('A mixed circuit with a measured 2 A total current',['The 2 Ω series resistor carries the 2 A supply current: its voltage drop is V = IR = 2 × 2 = 4 V.','The supply is 12 V, leaving 12 − 4 = 8 V across the parallel block.','Each 8 Ω branch has 8 V, so each branch carries I = V/R = 8/8 = 1 A.'],'Check: 1 A + 1 A = 2 A at the junction, and 4 V + 8 V = 12 V around either loop.')}`]],checks:[['In a series loop an ammeter reads 0.35 A before the first lamp. What will it read after the second lamp?','0.35 A: current is the same everywhere in a single series path.'],['A 12 V supply has two series lamps. A voltmeter across one reads 5 V. What is the voltage across the other?','7 V: the voltage drops add to 12 V.'],['Two resistors of 3 Ω and 5 Ω are in series. Find the total resistance.','3 + 5 = 8 Ω.'],['Two parallel lamps each connect directly across an ideal 9 V battery. What does a voltmeter across either lamp read?','9 V across each branch.'],['A supply ammeter reads 1.2 A before a junction. One branch ammeter reads 0.5 A. Find the current in the other branch.','0.7 A: the branch currents add to the supply current.'],['A 6 Ω resistor and a 3 Ω resistor are in parallel. Find the equivalent resistance.','2 Ω: at 6 V the branches carry 1 A and 2 A, so Rtotal = 6 V ÷ 3 A = 2 Ω.']],resource:'circuits'},
{id:'magnetism',name:'Magnetic fields',short:'Poles, lines and Earth',icon:'N S',intro:'Read and draw magnetic field diagrams and distinguish permanent from induced magnetism.',lessons:[
['Magnetic materials and interactions',`${bbcImage('https://ichef.bbci.co.uk/images/ic/976xn/p0b2srvk.jpg.webp','BBC photograph of bar magnet with marked north and south poles',bb('topics/z3sf8p3/articles/zh766g8'),'Every bar magnet has two poles')}<p>Like magnetic poles repel; unlike poles attract. A magnet can attract an unmagnetised ferromagnetic object because it induces magnetism in it. Iron, nickel and cobalt are ferromagnetic. An induced magnet has both poles while magnetised; the near end becomes the opposite pole to the approaching magnet, so attraction occurs regardless of which pole approaches. Some materials retain magnetism after the external field is removed; others lose most of it.</p>${model('A north pole approaches an iron nail',['The approaching north pole induces a south pole at the near end of the nail.','A north pole appears at the far end while the nail is magnetised.','The nearer unlike poles attract.'],'An induced magnet has both poles; attraction alone does not prove an object is a permanent magnet.')}${video('bHLsHjRMAsU','Year 11 Physics Permanent and Induced Magnets','Pause and explain why an induced magnet is attracted by either approaching pole.')}`],
['Magnetic field lines',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/z296yrd/large','BBC magnetic field diagram with arrows from north to south outside a bar magnet',bb('topics/zgw7vj6/articles/zc8qfdm'),'Field direction outside the magnet is north to south')}<p>A magnetic field is a region where a magnetic object experiences a force. Outside a bar magnet, field lines go from <strong>north to south</strong>; they form closed loops when the path inside the magnet is included. Closer line spacing indicates a stronger field, usually near the poles. The field weakens with distance. Straight, parallel, equally spaced lines indicate an approximately uniform field. Earth also has a magnetic field, which influences a compass needle.</p>${model('Read a field diagram',['Follow the arrows outside the magnet: they leave north and enter south.','Look for closely spaced lines near the poles: the field is stronger there.','If lines are straight, parallel and equally spaced, the field is approximately uniform.'],'Field lines show direction and relative strength, not the path a magnet physically travels.')}${video('3elpPfyHV0E','Year 11 Physics Magnets and Field Lines','Practise adding arrowheads in the right direction.')}`]],checks:[['A north pole approaches an unmagnetised iron nail. What is induced at the near end?','A south pole; the nail is attracted.'],['Does an induced magnet have only one pole?','No. It has north and south poles while magnetised.'],['What do closely spaced magnetic field lines show?','A stronger magnetic field.'],['In which direction do field lines point outside a bar magnet?','From north to south.']],resource:'magnet'},
{id:'electromagnet',name:'Current and magnetism',short:'Wires, solenoids and uses',icon:'◎',intro:'Predict the field around a wire and solenoid and explain electromagnet applications.',lessons:[
['Field around a wire',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/znp66g8/large','BBC diagram of circular magnetic field around current carrying wire',bb('topics/z3sf8p3/articles/z7922v4'),'Field around a current carrying wire')}<p>A current carrying straight wire produces concentric circular magnetic field lines. The field weakens farther from the wire. For <strong>conventional current</strong>, point your right thumb in the direction of current: your curled fingers show the direction of the magnetic field. A stronger current produces a stronger field. Parallel wires with currents in the same direction attract; in opposite directions they repel.</p>${model('Apply the right hand grip rule',['Point your right thumb in the direction of conventional current along the wire.','Curl your fingers around the wire: they show the direction of the circular field.','Move farther away: the field becomes weaker.'],'Use conventional current, not the electron flow direction.')}`],
['Solenoids and electromagnets',`${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zbbyydm/large','BBC diagram comparing fields around a solenoid and bar magnet',bb('topics/z3sf8p3/articles/z7922v4'),'Solenoid and bar magnet field patterns')}<p>A solenoid is a coil of wire. Its field resembles that of a bar magnet, with a relatively uniform field inside. Curl the fingers of your right hand in the conventional current's direction around the coil; your thumb points to its north pole. Looking at one end, anticlockwise current indicates a north pole; clockwise indicates south. More current or more turns produces a stronger field. Adding an iron core strengthens the field because the iron becomes magnetised.</p>${bbcImage('https://bam.files.bbci.co.uk/bam/live/content/zkkccmn/large','BBC electromagnet with wire wound around soft iron core',bb('topics/z3sf8p3/articles/z7922v4'),'Iron core strengthens the solenoid field')}<p>An electric bell or door lock uses a current controlled electromagnet to attract a moving iron part. Switching off the current weakens the field so a spring can return the part.</p>${model('Name the pole of a solenoid',['Look directly at one end and trace the conventional current around that end.','Anticlockwise current means that end is north; clockwise means south.','Adding turns, increasing current or adding a soft iron core strengthens the electromagnet.'],'When current switches off, the magnetic pull drops and the mechanism can return.')}${video('79_SF5AZtzo','Year 11 Physics Electromagnetism','Focus on the right hand grip rule, solenoid field and ways to strengthen an electromagnet.')}`]],checks:[['A straight wire carries conventional current upward. Which hand rule gives the field direction?','Right hand grip rule: thumb upward and curled fingers indicate the circular field.'],['Viewed from one end of a solenoid, current is anticlockwise. Which pole is that end?','North.'],['Give two ways to strengthen a solenoid electromagnet.','Increase current; increase number of turns per unit length; add a suitable soft iron core (any two).'],['Why can an electromagnet operate a door lock remotely?','Switching current on or off changes its magnetic field, which moves an iron armature or latch.']],resource:'magnet'}
];
const exam=[
['A neutral plastic rod is rubbed with a cloth. Electrons move from the cloth to the rod. State the charge on each and explain why. [3]','The rod gains electrons and becomes negative (1). The cloth loses electrons and becomes positive (1). Protons remain in the nuclei (1).','charge'],
['A charged rod attracts small neutral pieces of paper. Explain this observation using induced charge and distance. [4]','Charge is redistributed or polarised in the paper (1). The nearer side has opposite charge to the rod (1). The farther side has like charge (1). The attraction is stronger at the smaller separation than the repulsion, giving a net force toward the rod (1).','charge'],
['Explain how a cloud and ground can produce a lightning strike. Include charge separation, induced charge and the role of air. [4]','Charge separates in the cloud (1), inducing opposite charge on the ground (1). The large potential difference produces a strong electric field (1), which ionises the air so charge can flow as a spark (1).','charge'],
['A 9.0 V supply is connected across a fixed 3.0 Ω resistor. Calculate the current and the power transferred. Show working. [4]','I = V/R = 9.0/3.0 = 3.0 A (2). P = VI = 9.0 × 3.0 = 27 W (2).','circuits'],
['Describe how to connect an ammeter and voltmeter to measure the current through and potential difference across a lamp. Explain the resistance of each meter. [4]','Ammeter in series (1) with very low resistance (1). Voltmeter in parallel across the lamp (1) with very high resistance (1).','circuits'],
['A student graphs voltage V on the vertical axis against current I on the horizontal axis for a fixed resistor. The points (0.20 A, 1.0 V) and (0.60 A, 3.0 V) lie on a straight line. Find the resistance and explain the line’s shape. [4]','Gradient ΔV/ΔI = (3.0−1.0)/(0.60−0.20) (1) = 5.0 Ω (1). V is directly proportional to I (1) if temperature and resistance remain constant (1).','circuits'],
['A 12 V supply is connected to 2 Ω and 4 Ω resistors in series. Calculate total resistance, current and voltage across each resistor. [5]','Rtotal = 2 + 4 = 6 Ω (1). I = 12/6 = 2 A (1). V2Ω = 2×2 = 4 V (1). V4Ω = 2×4 = 8 V (1). The voltage drops add to 12 V (1).','networks'],
['Two parallel branches contain resistors of 6 Ω and 3 Ω. Each branch is directly across an ideal 6 V supply. Find each branch current and the total supply current. [4]','Each branch is at 6 V (1). I6Ω = 6/6 = 1 A (1). I3Ω = 6/3 = 2 A (1). Total = 3 A (1).','networks'],
['An iron nail is attracted by both ends of a bar magnet. Explain why this does not prove the nail is a permanent magnet. State a test that would show the nail is a magnet. [4]','The field induces magnetism in the nail (1). Its near end becomes the opposite pole, so either end attracts (1). Bring a known pole of a magnet toward both ends of the nail (1); repulsion at one end would show it has a fixed pole and is magnetised (1).','magnetism'],
['Describe the pattern and direction of field lines around a bar magnet. Explain how the diagram shows field strength. [3]','Lines emerge from north and enter south outside the magnet (1). Lines curve around and do not cross (1). Closer spacing near poles shows a stronger field (1).','magnetism'],
['State the magnetic field shape around a straight current carrying wire and explain how to determine its direction. What happens farther from the wire? [4]','Concentric circles centred on the wire (1). Right thumb in conventional current direction (1), curled fingers give field direction (1). Field strength decreases farther from the wire (1).','electromagnet'],
['A door lock uses a solenoid with an iron core. Explain how switching on the current releases the latch and give two ways to increase the pull. [5]','Current produces a magnetic field around the coil (1). The iron core becomes magnetised and strengthens the field (1). Magnetic attraction moves the iron armature/latch (1). Increase current (1) and increase turns per unit length (1).','electromagnet']
];
// Coverage additions checked against the supplied Year 11 Electricity unit plan.
const extendSection=(id,lessons,checks)=>{const section=sections.find(s=>s.id===id);section.lessons.push(...lessons);section.checks.push(...checks);};
extendSection('charge',[
['Charge, force and potential energy',`<p>Charge is measured in <strong>coulombs (C)</strong>. A proton has charge +1.60 × 10<sup>−19</sup> C and an electron −1.60 × 10<sup>−19</sup> C: equal size, opposite signs. Neutral means balanced charge, not no charged particles.</p><p>Electrostatic forces act without contact. Qualitatively, Coulomb’s law says more charge on either object means a stronger force, while greater distance means a weaker force. Compare the amount of charge and the separation to explain whether the force becomes stronger or weaker.</p><p>Electrical energy changes when charges move or are separated. Moving a charge towards a like charge requires work against repulsion and increases electric potential energy. Letting like charges separate lowers it. Moving opposite charges apart requires work against attraction; letting them approach lowers it. The electric force can do work as electric potential energy becomes movement or other forms of energy. <strong>Potential energy and voltage are different:</strong> voltage is energy transferred per unit charge.</p>${model('Identify an unknown charge',['Bring a known positive charge near the test object without touching.','Repulsion shows the test object is positive. Attraction alone is inconclusive because a neutral object can also be attracted.','Repeat with a known negative charge. Repulsion now shows the test object is negative.'],'Use repulsion with a known charge to identify the sign.')}`],
['Conductors, insulators and charge distribution',`<p>A conductor has mobile charge carriers; an insulator has no freely moving charge carriers under ordinary conditions. In a metal, electrons move throughout the material while the positive ions remain in place. Static electricity is a build-up of net charge; current electricity is a flow of charge, carried by electrons in metal wires.</p><p>On an isolated spherical conductor, excess charge spreads uniformly over the outer surface. On an irregular conductor it is <strong>non-uniform</strong>, concentrating most at sharp points, corners and edges. In an insulator, transferred charge stays mainly near where it was deposited, so charge distribution is often non-uniform.</p><p>Charging by friction separates charge; it does not create electrons. Charge cannot grow without limit: as charge accumulates, the electric field increasingly opposes further transfer, while leakage through air, moisture or a spark can discharge the object.</p>${model('Share charge by conduction',['A charged conductor touches a neutral conductor, providing a path for electrons.','For a negative conductor, electrons spread to the neutral one. For a positive conductor, electrons flow from the neutral one to it.','Charge redistributes until there is no potential difference driving further flow. Identical isolated spheres end with equal charge; different shapes and sizes need not.'],'Total charge is conserved. Redistribution reduces the system’s electric potential energy.')}`],
['Induction and lifting neutral paper',`<p>Polarisation separates charge within a neutral object without changing its total charge. Mobile electrons in a conductor can move across it; in an insulator, bound charges shift only slightly within atoms or molecules. Under comparable conditions this allows greater charge separation, and often stronger attraction, in a conductor.</p><p>To leave a conductor with a net induced charge: bring a charged rod near it, connect the conductor to Earth, <strong>disconnect Earth while the rod is still present</strong>, then remove the rod. A negative rod repels electrons to Earth and leaves the conductor positive; a positive rod draws electrons from Earth and leaves it negative. Without earthing, the isolated conductor is polarised but stays neutral overall.</p><p>A paper scrap lifts from the table when the upward electrostatic force is greater than its downward weight: <strong>F<sub>e</sub> &gt; F<sub>g</sub></strong>. The forces are unbalanced, so it accelerates upwards.</p>`],
['Earthing, electric shocks and discharge between materials',`<p>Earth is a very large charge reservoir. A conducting connection lets electrons leave a negatively charged object or enter a positively charged object. This reduces excess charge and the system’s electric potential energy.</p><p>A charged person can induce charge separation in a neutral metal object. As the finger approaches, the gap decreases and the electric field grows. A sufficient potential difference ionises the normally poorly conducting air, so charge moves rapidly across the gap as a spark: an electric shock.</p><p>In a storm, charge separation and induced charge create a large potential difference. Greater charge and a shorter gap make electrostatic interaction stronger. Tall objects shorten the gap to the cloud; sharp tips concentrate surface charge and strengthen the local field, making air breakdown more likely.</p><p>A spark can transfer charge between two insulators or between an insulator and a conductor. On an insulator it mainly changes charge near the discharge point because charge elsewhere cannot move freely. A conductor can redistribute charge throughout itself, allowing a more complete discharge, especially if earthed. An isolated conductor can still retain net charge after a spark.</p>`]
],[
['How much charge does one electron have, and in what unit?','−1.60 × 10⁻¹⁹ C, measured in coulombs. A proton has equal magnitude with positive sign.'],
['How can you distinguish a positive object from a neutral object using a known positive charge?','Repulsion proves the object is positive. Attraction alone does not: a neutral object can be polarised and attracted.'],
['What happens to electrostatic force as two charged objects move farther apart?','It becomes weaker, with the charges unchanged.'],
['Why does pushing two like charges closer together increase potential energy?','Work is done against their repulsive force, increasing the system’s electric potential energy.'],
['Compare excess charge on a spherical conductor, a pointed conductor and an insulator.','It is uniform on an isolated sphere; concentrated at sharp points on an irregular conductor; mostly localised near the charging site on an insulator.'],
['Why can rubbing an insulator not build up unlimited charge?','Increasing charge opposes further transfer; leakage or air breakdown can discharge it.'],
['What must be true for neutral paper to lift towards a rod above it?','The upward electrostatic force exceeds the paper’s weight: Fe > Fg.'],
['How is charging by induction different from polarising an isolated conductor?','Polarisation only redistributes existing charge. Earthing while the rod is present, then disconnecting Earth before removing the rod, can leave a net charge.'],
['Why does a conductor usually discharge more completely than an insulator?','Mobile electrons redistribute throughout the conductor; in an insulator charge away from the spark site cannot readily reach it.'],
['How does Earth discharge a negatively charged object?','Excess electrons flow from the object to Earth through a conducting connection.']
]);
extendSection('circuits',[
['What changes current, resistance and power?',`<p>For a fixed circuit resistance, a larger supply voltage transfers more energy per coulomb and gives a larger current: <strong>I = V/R</strong>. At fixed voltage, increasing resistance reduces current. A component’s resistance depends on its material and design; a longer wire has more resistance and a thicker wire has less. For metals, heating normally increases resistance. Additional parallel paths lower the circuit’s equivalent resistance; extra series components normally raise it.</p><p>Across a component, voltage measures the decrease in electric potential energy per charge as energy is transferred. For a fixed current, a greater resistance means a greater voltage drop, V = IR. At that same current, power is greater too because P = VI and the voltage drop has increased. <strong>Greater resistance does not always mean more heating:</strong> at fixed voltage, increasing resistance reduces current, so P = VI gives less power.</p><p>For the same fixed resistor, doubling current doubles its voltage drop and makes power four times as large. Power describes energy transferred each second: more power can mean brighter light, more heating or faster motion, depending on the component.</p><p>In an ideal ammeter, R = 0 so V = IR = 0. Real ammeters have a small resistance and a small voltage drop. An ideal voltmeter has infinite resistance and draws no current, yet has the voltage of the component across its terminals. Real voltmeters have very high resistance and draw a tiny current.</p>${model('Draw and check a measurement circuit',['Use standard symbols for a cell or supply, switch, lamp or resistor, ammeter and voltmeter.','Draw a complete loop with straight wires and put the ammeter in series with the component.','Connect the voltmeter across the component’s two terminals. Mark joined junctions clearly; crossing wires are not connected unless indicated.','Label conventional current from the positive supply terminal through the external circuit to the negative terminal.'],'A wire directly across the supply is a short circuit, not a safe measurement connection.')}`]
],[
['At fixed resistance, what happens to current if supply voltage doubles?','It doubles, because I = V/R.'],
['Give four factors that affect a metal wire’s resistance.','Material, length, cross-sectional area (thickness) and temperature. Longer, thinner or hotter wires generally have greater resistance.'],
['Does an ideal voltmeter have zero voltage across it?','No. It measures the voltage across its terminals while drawing no current. An ideal ammeter has zero voltage drop.'],
['The current through a fixed resistor doubles. What happens to voltage and power?','V = IR doubles; P = VI becomes four times as large because both V and I double.'],
['Does increasing resistance always increase heating?','No. At fixed current, greater resistance gives a greater voltage drop, so P = VI increases. At fixed voltage, greater resistance gives a smaller current, so P = VI decreases.']
]);
extendSection('networks',[
['Kirchhoff’s laws and changing mixed circuits',`<p><strong>Kirchhoff’s current law:</strong> total current entering any junction equals total current leaving it. This follows from conservation of charge. Total supply current is the current leaving one supply terminal and returning to the other.</p><p><strong>Kirchhoff’s voltage law:</strong> around a complete conducting loop, voltage gains equal voltage drops. This follows from conservation of energy. All parallel paths between the same two junctions have the same total voltage drop. That equals the supply voltage <strong>only when no other component in the loop takes a share of it</strong>.</p><p>Equal-resistance parallel paths carry equal current. A lower-resistance branch takes more current because each branch has the same voltage. An ideal zero-resistance path bypasses components across the same junctions, making their voltage and current zero. In a real short circuit, small wire and supply resistances limit a potentially dangerous large current. If a series resistor remains in the loop, it still limits total current.</p>${model('Add another branch to a mixed circuit',['Start with the diagram above: a 12 V supply, a 2 Ω series resistor and two 8 Ω parallel branches, with a measured total current of 2 A.','Add a third 8 Ω parallel branch. The additional conducting path reduces total resistance, so supply current increases.','The series resistor carries more current. V = IR means its voltage drop increases.','Kirchhoff’s voltage law means less of the 12 V supply remains across the parallel block.','Each original branch still has 8 Ω resistance. I = V/R means its current decreases because its voltage has decreased.'],'Adding a branch increases total current but reduces current in each original branch here, because the shared series resistor takes a larger voltage drop.')}`]
],[
['Two parallel branches have equal resistance. How is current shared?','Equally. If their resistances differ, the lower-resistance branch carries more current at the same branch voltage.'],
['What happens when a component is added in series at fixed supply voltage?','Total resistance increases and supply current decreases.'],
['What happens when a parallel path is added at fixed supply voltage?','Equivalent resistance decreases and supply current increases. In a mixed circuit, the branch voltage may also change.'],
['Why might the voltage across a parallel block be less than supply voltage?','Other components in series with the block take part of the supply voltage. Each loop’s voltage drops must add to the supply voltage.'],
['What happens if an ideal wire shorts one parallel resistor?','It shorts all components between those same junctions. Their voltage becomes zero and current bypasses them; remaining series resistance limits total current.']
]);
extendSection('magnetism',[
['Drawing Earth’s field and uniform fields',`<p>Magnetic fields are produced by permanent or induced magnets and by electric currents (moving charges). Ferromagnetic iron, nickel and cobalt can become magnetised when magnetic domains become more aligned.</p><p>To draw a bar magnet field, label N and S, draw curved closed field lines, and add arrows from N to S outside the magnet. Use closer spacing near the poles and wider spacing farther away. Lines never cross. A non-uniform field changes strength or direction; a uniform field is shown by straight, parallel, equally spaced lines, such as approximately between broad opposite poles.</p><p>To sketch Earth’s field, draw Earth with its geographical north at the top. Draw a dipole pattern like a bar magnet, with arrows outside Earth entering near geographical north and leaving near geographical south. The region near geographical north behaves like a magnetic <strong>south</strong> pole, attracting the north-seeking end of a compass. Earth’s magnetic and geographical axes are tilted relative to one another.</p>${model('Draw Earth’s magnetic field',['Draw and label geographical north and south on a circle representing Earth.','Sketch curved field lines looping around Earth; keep them closer together in the polar regions.','Add arrows entering near geographical north and leaving near geographical south.','Draw a compass tangent to a field line with its north-seeking end pointing along the field arrow.'],'This is an approximate dipole model, not an exact map of Earth’s changing field.')}`]
],[
['Name two sources of magnetic fields.','Magnets and electric currents (moving charges).'],
['How should field lines be drawn for a uniform magnetic field?','Straight, parallel and equally spaced, with arrows in the same direction.'],
['Which way do Earth’s external field lines point near geographical north?','Into Earth near geographical north, which behaves like a magnetic south pole.']
]);
extendSection('electromagnet',[
['Force on a current carrying wire and combining fields',`<p>A current carrying wire in an external magnetic field experiences a force. When the wire is <strong>perpendicular to the field</strong>, use <strong>F = BIL</strong>. F is force in newtons (N), B is magnetic flux density (field strength) in tesla (T), I is current in amperes (A), and L is the length of wire inside the magnetic field in metres (m). Use only the length within the field and convert centimetres to metres.</p><p>Rearrange to find <strong>B = F/(IL)</strong>, <strong>I = F/(BL)</strong>, or <strong>L = F/(BI)</strong>. With other quantities fixed, doubling B, I or L doubles the force. A wire parallel to the field experiences no magnetic force.</p>${model('Calculate the force',['A 0.20 m wire carries 3.0 A perpendicular to a 0.50 T field.','Write F = BIL and substitute F = 0.50 × 3.0 × 0.20.','F = 0.30 N.'],'L is the length inside the field, not necessarily the full wire length.')}${model('Calculate magnetic field strength',['A wire experiences 0.12 N while carrying 2.0 A; 15 cm of wire is perpendicular to the field.','Convert L = 15 cm = 0.15 m. Rearrange B = F/(IL).','B = 0.12/(2.0 × 0.15) = 0.40 T.'],'Use brackets around the whole denominator.')}<p>For parallel wires, apply the grip rule to <strong>each wire</strong> at the point you are considering. With currents in the same direction, the fields between the wires oppose and cancel at the midpoint if the currents are equal; outside they reinforce. The wires attract. With opposite currents, the fields between them reinforce; outside they oppose. The wires repel. Unequal opposing fields give a net field in the direction of the stronger contribution.</p><p>When drawing a wire field, use concentric circles with arrows from the grip rule and wider spacing farther away to show weakening field. A dot (⊙) represents conventional current out of the page: the field is anticlockwise. A cross (⊗) represents current into the page: the field is clockwise.</p>`],
['Loops, solenoids and electric bells',`<p>A single current loop has a north and south face. Viewed directly from one face, anticlockwise conventional current makes that face north; clockwise makes it south. For a solenoid, curl right fingers along current around the turns: the thumb indicates north. Draw field lines leaving N and entering S outside, and travelling from S to N through the coil’s interior. Inside a long solenoid, lines are close, parallel and approximately equally spaced.</p><p>Adding a soft iron core aligns its magnetic domains and strengthens the field. It loses most of its magnetism when current is switched off, which helps mechanisms release. More current or more turns per unit length also strengthens the field.</p>${model('Explain a repeating electric bell',['Closing the switch lets current flow through the coil, magnetising the soft iron core.','The electromagnet attracts the iron armature; the striker hits the bell.','The movement breaks the contact, opening the circuit and stopping current.','The core loses most of its magnetism, so a spring returns the armature and reconnects the contact.','The cycle repeats while the switch is held closed.'],'A lock can use the same magnetic pull to move a latch. Whether current locks or unlocks it depends on the mechanism’s design.')}`]
],[
['A 0.25 m wire carries 4.0 A perpendicular to a 0.30 T field. Calculate the force.','F = BIL = 0.30 × 4.0 × 0.25 = 0.30 N.'],
['A 0.10 m wire carries 3.0 A perpendicular to a field and experiences 0.15 N. Find B.','B = F/(IL) = 0.15/(3.0 × 0.10) = 0.50 T.'],
['A 0.20 m wire in a 0.40 T field experiences 0.16 N. Find I when the wire is perpendicular to the field.','I = F/(BL) = 0.16/(0.40 × 0.20) = 2.0 A.'],
['A wire carrying 5.0 A perpendicular to a 0.20 T field experiences 0.10 N. Find the length inside the field.','L = F/(BI) = 0.10/(0.20 × 5.0) = 0.10 m.'],
['Equal parallel currents point in the same direction. What happens to their fields at the midpoint?','They have equal magnitude and opposite directions, so cancel. The wires attract.'],
['Opposite parallel currents: what happens to the fields between the wires?','They reinforce because they point in the same direction there. The wires repel.'],
['Current comes out of the page through a wire. Which way does the field go?','Anticlockwise, using the right hand grip rule.'],
['Viewed from one face of a single loop, current is clockwise. Name that face’s pole.','South. The anticlockwise face is north.'],
['Why does an electric bell repeatedly stop and restart its current?','The attracted armature breaks the contact; the field weakens and a spring returns it, remaking the contact.']
]);
exam.push(
['Explain why a sharp conductor can spark more readily than a smooth spherical conductor. [3]','Charge is concentrated at sharp points (1), creating a stronger local electric field (1), which can ionise air and allow discharge (1).','charge'],
['Explain how a neutral conductor can be left positively charged using a negatively charged rod without touching it. [4]','Bring the rod near to repel electrons (1). Earth the conductor so electrons leave (1). Remove the Earth connection while the rod is present (1). Remove the rod; the electron deficit leaves positive charge (1).','charge'],
['A charged rod above a neutral paper scrap causes it to lift. Explain the charge separation and force condition. [4]','The paper is polarised (1). Opposite charge is nearer the rod (1), giving stronger attraction than the farther repulsion (1). The upward electrostatic force exceeds weight (1).','charge'],
['Explain why a spark between two charged insulators may leave more charge behind than a spark involving an earthed conductor. [3]','Charges cannot move freely through the insulators (1), so discharge is mainly local (1). Mobile electrons in the conductor can redistribute and flow to or from Earth (1).','charge'],
['The current through a fixed 4 Ω resistor increases from 1 A to 2 A. Calculate its voltage and power before and after. [4]','Before: V = 1 × 4 = 4 V (1), P = 4 × 1 = 4 W (1). After: V = 2 × 4 = 8 V (1), P = 8 × 2 = 16 W (1).','circuits'],
['A 12 V ideal supply feeds a 2 Ω series resistor and two parallel 8 Ω resistors. A third 8 Ω branch is added. Explain what happens to total current and current through each original branch. [5]','An additional path reduces total resistance (1), so total current increases at fixed supply voltage (1). The series resistor’s voltage drop increases because V = IR (1). Less voltage remains across the parallel block by Kirchhoff’s voltage law (1). Each original branch has the same resistance but a lower voltage, so its current decreases by I = V/R (1).','networks'],
['Sketch Earth’s magnetic field and label geographical north and south. State the direction of the external field near geographical north. [3]','Dipole-like curved lines around Earth (1), labelled geographical poles with lines more concentrated near polar regions (1), and arrows entering near geographical north and leaving near geographical south (1).','magnetism'],
['A wire carries 2.5 A perpendicular to a uniform magnetic field. A 12 cm length inside the field experiences a force of 0.18 N. Calculate the magnetic field strength. [3]','L = 0.12 m (1). Rearrange F = BIL to B = F/(IL) (1). B = 0.18/(2.5 × 0.12) = 0.60 T (1).','electromagnet'],
['A wire has 30 cm inside a 0.40 T field and carries 2.0 A perpendicular to the field. Calculate the force, then state the force if the current doubles. [4]','L = 0.30 m (1). F = BIL = 0.40 × 2.0 × 0.30 (1) = 0.24 N (1). Doubling current doubles force to 0.48 N (1).','electromagnet'],
['Compare the magnetic fields between two parallel wires carrying equal currents in the same direction and then in opposite directions. [4]','Same direction: the fields oppose between the wires (1) and cancel at the midpoint (1). Opposite directions: the fields point the same way between the wires (1) and reinforce (1).','electromagnet'],
['Explain the repeating action of an electric bell. [4]','Current magnetises the core (1). It attracts the armature, striking the bell and breaking contact (1). Current stops and the magnetic pull weakens (1). A spring returns the armature, remaking contact so the cycle repeats (1).','electromagnet']
);

let active='charge',tab='learn';const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function render(){const s=sections.find(x=>x.id===active);document.querySelector('#topics').innerHTML=sections.map(x=>`<button data-topic="${x.id}" class="${x.id===active?'active':''}" aria-current="${x.id===active?'true':'false'}"><strong>${x.icon} &nbsp;${x.name}</strong><small>${x.short}</small></button>`).join('');document.querySelectorAll('.tabs button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));let body=`<div class="section-head"><p class="eyebrow">${s.name.toUpperCase()}</p><h2>${tab==='exam'?'Exam Practice':tab==='check'?'Quick Check':s.name}</h2><p>${tab==='learn'?s.intro:tab==='check'?'Try each question before revealing the model answer.':`Practice original exam style questions. Mark values guide the level of detail.`}</p></div>`;
if(tab==='learn'){body+=s.lessons.map(([title,html])=>`<article class="card"><h3>${title}</h3>${html}</article>`).join('');}
else{const list=tab==='check'?s.checks.map(([q,a])=>[q,a]):exam.filter(q=>q[2]===s.id).map(([q,a])=>[q,a]);body+=`<div class="check-list">${list.map(([q,a],i)=>`<article class="card ${tab==='exam'?'exam':''}"><div class="question">${i+1}. ${esc(q)}</div>${tab==='exam'?'<div class="answer-lines"></div><div class="answer-lines"></div><div class="answer-lines"></div>':''}<button class="reveal" type="button" aria-expanded="false">Show model answer</button><div class="answer" hidden>${esc(a)}</div></article>`).join('')}</div>`}
document.querySelector('#content').innerHTML=body}
document.addEventListener('click',e=>{const topic=e.target.closest('[data-topic]'),mode=e.target.closest('[data-tab]'),reveal=e.target.closest('.reveal');if(topic){active=topic.dataset.topic;render()}if(mode){tab=mode.dataset.tab;render()}if(reveal){const ans=reveal.nextElementSibling;ans.hidden=!ans.hidden;reveal.setAttribute('aria-expanded',String(!ans.hidden));reveal.textContent=ans.hidden?'Show model answer':'Hide model answer'}});render();
